package org.rsmod.api.db

import java.sql.Connection
import java.sql.PreparedStatement

@Suppress("SqlSourceToSinkFlow")
public class DatabaseConnection(private val connection: Connection) {
    public fun prepareStatement(sql: String): PreparedStatement {
        return connection.prepareStatement(sql)
    }

    public fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement {
        return connection.prepareStatement(sql, autoGeneratedKeys)
    }
}
