[versions]
clikt = "3.4.2"
guava = "31.1-jre"
guice = "5.1.0"
inline-logger = "1.0.3"
junit = "5.8.2"
kotlin-coroutines = "1.6.3"
kotlinter = "3.9.0"
logback = "1.2.11"
netty = "4.1.77.Final"

[plugins]
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
inlineLogger = { module = "com.michael-bull.kotlin-inline-logger:kotlin-inline-logger-jvm", version.ref = "inline-logger" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotlinCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
nettyBuffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
nettyCodecCore = { module = "io.netty:netty-codec", version.ref = "netty" }
nettyHandler = { module = "io.netty:netty-handler", version.ref = "netty" }
nettyTransport = { module = "io.netty:netty-transport", version.ref = "netty" }
