@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import org.rsmod.api.type.refs.obj.ObjReferences

typealias objs = BaseObjs

object BaseObjs : ObjReferences() {
    val template_for_cert = find("template_for_cert")
    val template_for_transform = find("template_for_transform")
    val template_for_placeholder = find("template_for_placeholder")
    val null_item_placeholder = find("null_item_placeholder")

    val coins = find("coins")
    val bones = find("bones")

    val music_cape = find("music_cape")
    val music_cape_t = find("music_cape_t")
    val music_hood = find("music_hood")
    val quest_point_cape = find("quest_point_cape")
    val quest_point_cape_t = find("quest_point_cape_t")
    val quest_point_hood = find("quest_point_hood")
    val achievement_diary_cape = find("achievement_diary_cape")
    val achievement_diary_cape_t = find("achievement_diary_cape_t")
    val achievement_diary_hood = find("achievement_diary_hood")
    val cabbage_cape = find("cabbage_cape")
    val max_hood = find("max_hood")
    val max_cape_worn = find("max_cape_worn")
    val max_cape_inv = find("max_cape_inv")

    val helm_of_neitiznot = find("helm_of_neitiznot")
    val fire_cape = find("fire_cape")
    val amulet_of_fury = find("amulet_of_fury")
    val abyssal_whip = find("abyssal_whip")
    val bandos_chestplate = find("bandos_chestplate")
    val dragon_defender = find("dragon_defender")
    val bandos_tassets = find("bandos_tassets")
    val barrows_gloves = find("barrows_gloves")
    val dragon_boots = find("dragon_boots")
    val berserker_ring = find("berserker_ring")
    val adamant_arrow = find("adamant_arrow")
    val rune_arrow = find("rune_arrow")
    val rune_kiteshield = find("rune_kiteshield")
    val dragon_claws = find("dragon_claws")
    val crystal_shield = find("crystal_shield")
    val dragon_longsword = find("dragon_longsword")

    val pot_empty = find("pot_empty")
    val jug_empty = find("jug_empty")
    val pack_jug_empty = find("pack_jug_empty")
    val shears = find("shears")
    val knife = find("knife")
    val bucket_empty = find("bucket_empty")
    val bucket_of_milk = find("bucket_of_milk")
    val pack_bucket = find("pack_bucket")
    val bowl_empty = find("bowl_empty")
    val cake_tin = find("cake_tin")
    val tinderbox = find("tinderbox")
    val chisel = find("chisel")
    val spade = find("spade")
    val hammer = find("hammer")
    val newcomer_map = find("newcomer_map")
    val sos_security_book = find("sos_security_book")
    val wool = find("wool")

    val cabbage = find("cabbage")
    val onion = find("onion")
    val grain = find("grain")
    val potato = find("potato")
    val cabbage_seed = find("cabbage_seed")
    val egg = find("egg")

    val bobs_axe_flyer = find("bobs_axe_flyer")
    val bronze_pickaxe = find("bronze_pickaxe")
    val iron_battleaxe = find("iron_battleaxe")
    val steel_battleaxe = find("steel_battleaxe")
    val mithril_battleaxe = find("mithril_battleaxe")
    val beer = find("beer")
    val charcoal = find("charcoal")

    val logs = find("logs")
    val oak_logs = find("oak_logs")
    val willow_logs = find("willow_logs")
    val maple_logs = find("maple_logs")
    val yew_logs = find("yew_logs")
    val magic_logs = find("magic_logs")
    val redwood_logs = find("redwood_logs")
    val teak_logs = find("teak_logs")
    val mahogany_logs = find("mahogany_logs")
    val achey_tree_logs = find("achey_tree_logs")
    val arctic_pine_logs = find("arctic_pine_logs")
    val juniper_logs = find("juniper_logs")
    val bark = find("bark")

    val bronze_axe = find("bronze_axe")
    val iron_axe = find("iron_axe")
    val steel_axe = find("steel_axe")
    val black_axe = find("black_axe")
    val mithril_axe = find("mithril_axe")
    val adamant_axe = find("adamant_axe")
    val blessed_axe = find("blessed_axe")
    val rune_axe = find("rune_axe")
    val gilded_axe = find("gilded_axe")
    val dragon_axe = find("dragon_axe")
    val dragon_axe_or = find("dragon_axe_or")
    val third_age_axe = find("3rd_age_axe")
    val infernal_axe = find("infernal_axe")
    val infernal_axe_or = find("infernal_axe_or")
    val crystal_axe = find("crystal_axe")

    val shrimps = find("shrimps")
    val raw_herring = find("raw_herring")
    val herring = find("herring")

    val skull_sceptre_i = find("skull_sceptre_i")
    val ibans_staff = find("ibans_staff")
    val ibans_staff_u = find("ibans_staff_u")
    val slayers_staff = find("slayers_staff")
    val slayers_staff_e = find("slayers_staff_e")
    val thammarons_sceptre_a = find("thammarons_sceptre_a")
    val accursed_sceptre_a = find("accursed_sceptre_a")
    val staff_of_the_dead = find("staff_of_the_dead")
    val toxic_staff_of_the_dead = find("toxic_staff_of_the_dead")
    val staff_of_light = find("staff_of_light")
    val staff_of_balance = find("staff_of_balance")
    val void_knight_mace = find("void_knight_mace")
    val void_knight_mace_l = find("void_knight_mace_l")

    val spell_crumble_undead = find("crumble_undead_spell")
    val spell_iban_blast = find("iban_blast_spell")
    val spell_magic_dart = find("magic_dart_spell")
    val spell_flames_of_zamorak = find("flames_of_zamorak_spell")
    val spell_saradomin_strike = find("saradomin_strike_spell")
    val spell_claws_of_guthix = find("claws_of_guthix_spell")

    val woodcutting_icon = find("dummyitem_woodcutting_icon", 2122627481130992920)
    val bank_icon = find("dummyitem_bank_icon", 7806876055985215263)
    val furnace_icon = find("dummyitem_furnace_icon", 937693285129466531)
    val mining_icon = find("dummyitem_mining_icon", 1887266795659978258)
    val smithing_icon = find("dummyitem_smithing_icon", 5958751754372942517)
}
