@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import org.rsmod.api.type.refs.obj.ObjReferences

typealias objs = BaseObjs

object BaseObjs : ObjReferences() {
    val template_for_cert = find("template_for_cert")
    val template_for_transform = find("template_for_transform")
    val template_for_placeholder = find("template_for_placeholder")
    val null_item_placeholder = find("null_item_placeholder")

    val coins = find("coins")
    val bones = find("bones")

    val music_cape = find("music_cape")
    val music_cape_t = find("music_cape_t")
    val music_hood = find("music_hood")
    val quest_point_cape = find("quest_point_cape")
    val quest_point_cape_t = find("quest_point_cape_t")
    val quest_point_hood = find("quest_point_hood")
    val achievement_diary_cape = find("achievement_diary_cape")
    val achievement_diary_cape_t = find("achievement_diary_cape_t")
    val achievement_diary_hood = find("achievement_diary_hood")
    val cabbage_cape = find("cabbage_cape")
    val max_hood = find("max_hood")
    val max_cape_worn = find("max_cape_worn")
    val max_cape_inv = find("max_cape_inv")

    val helm_of_neitiznot = find("helm_of_neitiznot")
    val fire_cape = find("fire_cape")
    val amulet_of_fury = find("amulet_of_fury")
    val abyssal_whip = find("abyssal_whip")
    val fighter_torso = find("fighter_torso")
    val bandos_chestplate = find("bandos_chestplate")
    val dragon_defender = find("dragon_defender")
    val bandos_tassets = find("bandos_tassets")
    val barrows_gloves = find("barrows_gloves")
    val dragon_boots = find("dragon_boots")
    val berserker_ring = find("berserker_ring")
    val adamant_arrow = find("adamant_arrow")
    val rune_arrow = find("rune_arrow")
    val rune_kiteshield = find("rune_kiteshield")
    val dragon_claws = find("dragon_claws")
    val crystal_shield = find("crystal_shield")
    val dragon_longsword = find("dragon_longsword")

    val pot_empty = find("pot_empty")
    val jug_empty = find("jug_empty")
    val pack_jug_empty = find("pack_jug_empty")
    val shears = find("shears")
    val knife = find("knife")
    val bucket_empty = find("bucket_empty")
    val bucket_of_milk = find("bucket_of_milk")
    val pack_bucket = find("pack_bucket")
    val bowl_empty = find("bowl_empty")
    val cake_tin = find("cake_tin")
    val tinderbox = find("tinderbox")
    val chisel = find("chisel")
    val spade = find("spade")
    val hammer = find("hammer")
    val newcomer_map = find("newcomer_map")
    val sos_security_book = find("sos_security_book")
    val wool = find("wool")

    val cabbage = find("cabbage")
    val onion = find("onion")
    val grain = find("grain")
    val potato = find("potato")
    val cabbage_seed = find("cabbage_seed")
    val egg = find("egg")

    val bobs_axe_flyer = find("bobs_axe_flyer")
    val iron_battleaxe = find("iron_battleaxe")
    val steel_battleaxe = find("steel_battleaxe")
    val mithril_battleaxe = find("mithril_battleaxe")
    val beer = find("beer")
    val charcoal = find("charcoal")

    val logs = find("logs")
    val oak_logs = find("oak_logs")
    val willow_logs = find("willow_logs")
    val maple_logs = find("maple_logs")
    val yew_logs = find("yew_logs")
    val magic_logs = find("magic_logs")
    val redwood_logs = find("redwood_logs")
    val teak_logs = find("teak_logs")
    val mahogany_logs = find("mahogany_logs")
    val achey_tree_logs = find("achey_tree_logs")
    val arctic_pine_logs = find("arctic_pine_logs")
    val juniper_logs = find("juniper_logs")
    val bark = find("bark")

    val bronze_axe = find("bronze_axe")
    val iron_axe = find("iron_axe")
    val steel_axe = find("steel_axe")
    val black_axe = find("black_axe")
    val mithril_axe = find("mithril_axe")
    val adamant_axe = find("adamant_axe")
    val blessed_axe = find("blessed_axe")
    val rune_axe = find("rune_axe")
    val gilded_axe = find("gilded_axe")
    val dragon_axe = find("dragon_axe")
    val dragon_axe_or = find("dragon_axe_or")
    val third_age_axe = find("3rd_age_axe")
    val infernal_axe = find("infernal_axe")
    val infernal_axe_or = find("infernal_axe_or")
    val crystal_axe = find("crystal_axe")

    val bronze_pickaxe = find("bronze_pickaxe")
    val dragon_pickaxe = find("dragon_pickaxe")
    val dragon_pickaxe_upgraded = find("dragon_pickaxe_upgraded")
    val dragon_pickaxe_or_trailblazer = find("dragon_pickaxe_or")
    val dragon_pickaxe_or_zalcano = find("dragon_pickaxe_or_zalcano")
    val infernal_pickaxe = find("infernal_pickaxe")
    val infernal_pickaxe_uncharged = find("infernal_pickaxe_uncharged")
    val infernal_pickaxe_or = find("infernal_pickaxe_or")
    val infernal_pickaxe_or_uncharged = find("infernal_pickaxe_or_uncharged")
    val third_age_pickaxe = find("3rd_age_pickaxe")
    val crystal_pickaxe = find("crystal_pickaxe")

    val dragon_harpoon = find("dragon_harpoon")
    val dragon_harpoon_or = find("dragon_harpoon_or")
    val infernal_harpoon = find("infernal_harpoon")
    val infernal_harpoon_or = find("infernal_harpoon_or")
    val infernal_harpoon_or_uncharged = find("infernal_harpoon_or_uncharged")
    val crystal_harpoon = find("crystal_harpoon")

    val shrimps = find("shrimps")
    val raw_herring = find("raw_herring")
    val herring = find("herring")

    val skull_sceptre_i = find("skull_sceptre_i")
    val ibans_staff = find("ibans_staff")
    val ibans_staff_u = find("ibans_staff_u")
    val slayers_staff = find("slayers_staff")
    val slayers_staff_e = find("slayers_staff_e")
    val thammarons_sceptre_a = find("thammarons_sceptre_a")
    val accursed_sceptre_a = find("accursed_sceptre_a")
    val staff_of_the_dead = find("staff_of_the_dead")
    val toxic_staff_of_the_dead = find("toxic_staff_of_the_dead")
    val staff_of_light = find("staff_of_light")
    val staff_of_balance = find("staff_of_balance")
    val void_knight_mace = find("void_knight_mace")
    val void_knight_mace_l = find("void_knight_mace_l")

    val spell_crumble_undead = find("crumble_undead_spell")
    val spell_iban_blast = find("iban_blast_spell")
    val spell_magic_dart = find("magic_dart_spell")
    val spell_flames_of_zamorak = find("flames_of_zamorak_spell")
    val spell_saradomin_strike = find("saradomin_strike_spell")
    val spell_claws_of_guthix = find("claws_of_guthix_spell")

    val soulreaper_axe = find("soulreaper_axe")
    val amulet_of_avarice = find("amulet_of_avarice")
    val salve_amulet = find("salve_amulet")
    val salve_amulet_i = find("salve_amulet_i")
    val salve_amulet_e = find("salve_amulet_e")
    val salve_amulet_ei = find("salve_amulet_ei")
    val berserker_necklace = find("berserker_necklace")
    val berserker_necklace_or = find("berserker_necklace_or")

    val arclight = find("arclight")
    val silverlight = find("silverlight_6745")
    val burning_claws = find("burning_claws")
    val obsidian_helmet = find("obsidian_helmet")
    val obsidian_platebody = find("obsidian_platebody")
    val obsidian_platelegs = find("obsidian_platelegs")
    val toktz_xil_ek = find("toktz_xil_ek")
    val toktz_xil_ak = find("toktz_xil_ak")
    val tzhaar_ket_em = find("tzhaar_ket_em")
    val tzhaar_ket_om = find("tzhaar_ket_om")
    val tzhaar_ket_om_t = find("tzhaar_ket_om_t")
    val dragon_hunter_lance = find("dragon_hunter_lance")
    val dragon_hunter_wand = find("dragon_hunter_wand")
    val barronite_mace = find("barronite_mace")
    val barronite_mace_l = find("barronite_mace_l")
    val viggoras_chainmace = find("viggoras_chainmace")
    val ursine_chainmace = find("ursine_chainmace")
    val leafbladed_sword = find("leafbladed_sword")
    val leafbladed_spear = find("leafbladed_spear")
    val leafbladed_battleaxe = find("leafbladed_battleaxe")
    val colossal_blade = find("colossal_blade")
    val bone_mace = find("bone_mace")
    val gadderhammer = find("gadderhammer")
    val elysian_spirit_shield = find("elysian_spirit_shield")
    val dinhs_bulwark = find("dinhs_bulwark")
    val dinhs_blazing_bulwark = find("dinhs_blazing_bulwark")
    val osmumtens_fang = find("osmumtens_fang")
    val osmumtens_fang_or = find("osmumtens_fang_or")
    val infernal_cape = find("infernal_cape")
    val amulet_of_rancour = find("amulet_of_rancour")
    val radas_blessing_4 = find("radas_blessing_4")
    val primordial_boots = find("primordial_boots")
    val ferocious_gloves = find("ferocious_gloves")
    val ultor_ring = find("ultor_ring")
    val ghrazi_rapier = find("ghrazi_rapier")

    val inquisitors_great_helm = find("inquisitors_great_helm")
    val inquisitors_hauberk = find("inquisitors_hauberk")
    val inquisitors_plateskirt = find("inquisitors_plateskirt")
    val inquisitors_mace = find("inquisitors_mace")

    val justiciar_faceguard = find("justiciar_faceguard")
    val justiciar_chestguard = find("justiciar_chestguard")
    val justiciar_legguards = find("justiciar_legguards")

    val torva_full_helm = find("torva_full_helm")
    val torva_platebody = find("torva_platebody")
    val torva_platelegs = find("torva_platelegs")

    val keris = find("keris")
    val keris_p = find("keris_p")
    val keris_p_plus = find("keris_p_plus")
    val keris_p_plus_plus = find("keris_p_plus_plus")
    val keris_partisan = find("keris_partisan")
    val keris_partisan_of_breaching = find("keris_partisan_of_breaching")
    val keris_partisan_of_corruption = find("keris_partisan_of_corruption")
    val keris_partisan_of_the_sun = find("keris_partisan_of_the_sun")

    val void_mage_helm = find("void_mage_helm")
    val void_ranger_helm = find("void_ranger_helm")
    val void_melee_helm = find("void_melee_helm")
    val void_top = find("void_knight_top")
    val void_robe = find("void_knight_robe")
    val void_gloves = find("void_knight_gloves")
    val elite_void_top = find("elite_void_top")
    val elite_void_robe = find("elite_void_robe")

    val void_mage_helm_l = find("void_mage_helm_l")
    val void_ranger_helm_l = find("void_ranger_helm_l")
    val void_melee_helm_l = find("void_melee_helm_l")
    val void_top_l = find("void_knight_top_l")
    val void_robe_l = find("void_knight_robe_l")
    val void_gloves_l = find("void_knight_gloves_l")
    val elite_void_top_l = find("elite_void_top_l")
    val elite_void_robe_l = find("elite_void_robe_l")

    val void_mage_helm_or = find("void_mage_helm_or")
    val void_ranger_helm_or = find("void_ranger_helm_or")
    val void_melee_helm_or = find("void_melee_helm_or")
    val void_top_or = find("void_knight_top_or")
    val void_robe_or = find("void_knight_robe_or")
    val void_gloves_or = find("void_knight_gloves_or")
    val elite_void_top_or = find("elite_void_top_or")
    val elite_void_robe_or = find("elite_void_robe_or")

    val void_mage_helm_l_or = find("void_mage_helm_l_or")
    val void_ranger_helm_l_or = find("void_ranger_helm_l_or")
    val void_melee_helm_l_or = find("void_melee_helm_l_or")
    val void_top_l_or = find("void_knight_top_l_or")
    val void_robe_l_or = find("void_knight_robe_l_or")
    val void_gloves_l_or = find("void_knight_gloves_l_or")
    val elite_void_top_l_or = find("elite_void_top_l_or")
    val elite_void_robe_l_or = find("elite_void_robe_l_or")

    val dharoks_helm_100 = find("dharoks_helm_100")
    val dharoks_helm_75 = find("dharoks_helm_75")
    val dharoks_helm_50 = find("dharoks_helm_50")
    val dharoks_helm_25 = find("dharoks_helm_25")

    val dharoks_platebody_100 = find("dharoks_platebody_100")
    val dharoks_platebody_75 = find("dharoks_platebody_75")
    val dharoks_platebody_50 = find("dharoks_platebody_50")
    val dharoks_platebody_25 = find("dharoks_platebody_25")

    val dharoks_platelegs_100 = find("dharoks_platelegs_100")
    val dharoks_platelegs_75 = find("dharoks_platelegs_75")
    val dharoks_platelegs_50 = find("dharoks_platelegs_50")
    val dharoks_platelegs_25 = find("dharoks_platelegs_25")

    val dharoks_greataxe_100 = find("dharoks_greataxe_100")
    val dharoks_greataxe_75 = find("dharoks_greataxe_75")
    val dharoks_greataxe_50 = find("dharoks_greataxe_50")
    val dharoks_greataxe_25 = find("dharoks_greataxe_25")

    val torags_helm_100 = find("torags_helm_100")
    val torags_helm_75 = find("torags_helm_75")
    val torags_helm_50 = find("torags_helm_50")
    val torags_helm_25 = find("torags_helm_25")

    val torags_platebody_100 = find("torags_platebody_100")
    val torags_platebody_75 = find("torags_platebody_75")
    val torags_platebody_50 = find("torags_platebody_50")
    val torags_platebody_25 = find("torags_platebody_25")

    val torags_platelegs_100 = find("torags_platelegs_100")
    val torags_platelegs_75 = find("torags_platelegs_75")
    val torags_platelegs_50 = find("torags_platelegs_50")
    val torags_platelegs_25 = find("torags_platelegs_25")

    val torags_hammers_100 = find("torags_hammers_100")
    val torags_hammers_75 = find("torags_hammers_75")
    val torags_hammers_50 = find("torags_hammers_50")
    val torags_hammers_25 = find("torags_hammers_25")

    val veracs_helm_100 = find("veracs_helm_100")
    val veracs_helm_75 = find("veracs_helm_75")
    val veracs_helm_50 = find("veracs_helm_50")
    val veracs_helm_25 = find("veracs_helm_25")

    val veracs_brassard_100 = find("veracs_brassard_100")
    val veracs_brassard_75 = find("veracs_brassard_75")
    val veracs_brassard_50 = find("veracs_brassard_50")
    val veracs_brassard_25 = find("veracs_brassard_25")

    val veracs_plateskirt_100 = find("veracs_plateskirt_100")
    val veracs_plateskirt_75 = find("veracs_plateskirt_75")
    val veracs_plateskirt_50 = find("veracs_plateskirt_50")
    val veracs_plateskirt_25 = find("veracs_plateskirt_25")

    val veracs_flail_100 = find("veracs_flail_100")
    val veracs_flail_75 = find("veracs_flail_75")
    val veracs_flail_50 = find("veracs_flail_50")
    val veracs_flail_25 = find("veracs_flail_25")

    val amulet_of_the_damned_full = find("amulet_of_the_damned_full")

    val woodcutting_icon = find("dummyitem_woodcutting_icon", 2122627481130992920)
    val bank_icon = find("dummyitem_bank_icon", 7806876055985215263)
    val furnace_icon = find("dummyitem_furnace_icon", 937693285129466531)
    val mining_icon = find("dummyitem_mining_icon", 1887266795659978258)
    val smithing_icon = find("dummyitem_smithing_icon", 5958751754372942517)
}
