plugins {
    id("base-conventions")
}

dependencies {
    implementation(libs.bouncycastle.provider)
    implementation(libs.bundles.logging)
    implementation(libs.fastutil)
    implementation(libs.guice)
    implementation(libs.netty.buffer)
    implementation(libs.openrs2.cache)
    implementation(libs.rsprot.api)
    implementation(libs.rsprot.shared)
    implementation(projects.api.account)
    implementation(projects.api.config)
    implementation(projects.api.cache)
    implementation(projects.api.core)
    implementation(projects.api.gameProcess)
    implementation(projects.api.market)
    implementation(projects.api.npc)
    implementation(projects.api.player)
    implementation(projects.api.playerOutput)
    implementation(projects.api.pwHash)
    implementation(projects.api.registry)
    implementation(projects.api.serverConfig)
    implementation(projects.api.totp)
    implementation(projects.api.type.typeReferences)
    implementation(projects.api.type.typeBuilders)
    implementation(projects.api.type.typeScriptDsl)
    implementation(projects.engine.annotations)
    implementation(projects.engine.coroutine)
    implementation(projects.engine.events)
    implementation(projects.engine.game)
    implementation(projects.engine.map)
    implementation(projects.engine.routefinder)
    implementation(projects.engine.plugin)
    implementation(projects.server.services)
}
