package org.rsmod.api.db.util

import java.sql.PreparedStatement
import org.rsmod.api.db.Database

@Suppress("SqlSourceToSinkFlow")
public suspend fun Database.prepareStatement(query: String): PreparedStatement {
    return withConnection { connection -> connection.prepareStatement(query) }
}

@Suppress("SqlSourceToSinkFlow")
public suspend fun Database.prepareStatement(
    query: String,
    autoGeneratedKeys: Int,
): PreparedStatement {
    return withConnection { connection -> connection.prepareStatement(query, autoGeneratedKeys) }
}
