package org.rsmod.api.spells.configs

import org.rsmod.api.config.refs.params
import org.rsmod.api.type.editors.obj.ObjEditor
import org.rsmod.map.CoordGrid

internal object SpellObjEditor : ObjEditor() {
    init {
        editStandardSpells()
        editAncientSpells()
        editLunarSpells()
        editArceuusSpells()
    }

    private fun editStandardSpells() {
        spell("view_jewellery_enchantment_spells", 0.0, suffix = "")
        spell("lumbridge_home_teleport", 0.0)
        spell("wind_strike", 5.5)
        spell("confuse", 13.0)
        spell("enchant_crossbow_bolt", 0.0)
        spell("water_strike", 7.5)
        spell("lvl_1_enchant", 17.5)
        spell("earth_strike", 9.5)
        spell("weaken", 21.0)
        spell("fire_strike", 11.5)
        spell("bones_to_bananas", 25.0)
        spell("wind_bolt", 13.5)
        spell("curse", 29.0)
        spell("bind", 30.0)
        spell("low_level_alchemy", 31.0)
        spell("water_bolt", 16.5)
        tele("varrock_teleport", 35.0, CoordGrid(0, 50, 53, 13, 32))
        spell("lvl_2_enchant", 37.0)
        spell("earth_bolt", 19.5)
        tele("lumbridge_teleport", 41.0, CoordGrid(0, 50, 50, 21, 18))
        spell("telekinetic_grab", 43.0)
        spell("fire_bolt", 22.5)
        tele("falador_teleport", 47.0, CoordGrid(0, 46, 52, 21, 50))
        spell("crumble_undead", 24.5)
        spell("teleport_to_house", 30.0)
        spell("wind_blast", 25.5)
        spell("superheat_item", 53.0)
        tele("camelot_teleport", 55.5, CoordGrid(0, 43, 54, 5, 22))
        spell("water_blast", 28.5)
        tele("kourend_castle_teleport", 58.0, CoordGrid(0, 25, 57, 41, 25))
        spell("lvl_3_enchant", 59.0)
        spell("iban_blast", 30.0)
        spell("snare", 60.0)
        spell("magic_dart", 30.0)
        tele("ardougne_teleport", 61.0, CoordGrid(0, 41, 51, 37, 38))
        spell("earth_blast", 31.5)
        tele("civitas_illa_fortis_teleport", 64.0, CoordGrid(0, 26, 48, 17, 61))
        spell("high_level_alchemy", 65.0)
        spell("charge_water_orb", 56.0)
        spell("lvl_4_enchant", 67.0)
        tele("watchtower_teleport", 68.0, CoordGrid(0, 45, 73, 53, 40))
        spell("fire_blast", 34.5)
        spell("charge_earth_orb", 70.0)
        spell("bones_to_peaches", 35.5)
        spell("saradomin_strike", 35.0)
        spell("flames_of_zamorak", 35.0)
        spell("claws_of_guthix", 35.0)
        tele("trollheim_teleport", 68.0, CoordGrid(0, 45, 57, 10, 31))
        spell("wind_wave", 36.0)
        spell("charge_fire_orb", 73.0)
        tele("ape_atoll_teleport", 74.0, CoordGrid(0, 43, 43, 45, 46))
        spell("water_wave", 37.5)
        spell("charge_air_orb", 76.0)
        spell("vulnerability", 76.0)
        spell("lvl_5_enchant", 78.0)
        spell("earth_wave", 40.0)
        spell("enfeeble", 83.0)
        spell("teleother_lumbridge", 84.0)
        spell("fire_wave", 42.5)
        spell("entangle", 89.0)
        spell("stun", 90.0)
        spell("charge", 180.0)
        spell("wind_surge", 44.5)
        spell("teleother_falador", 92.0)
        spell("water_surge", 46.5)
        spell("tele_block", 80.0)
        spell("teleport_to_target", 45.0)
        spell("lvl_6_enchant", 97.0)
        spell("teleother_camelot", 100.0)
        spell("earth_surge", 48.5)
        spell("lvl_7_enchant", 110.0)
        spell("fire_surge", 50.5)
    }

    private fun editAncientSpells() {
        spell("edgeville_home_teleport", 0.0)
        spell("smoke_rush", 30.0)
        spell("shadow_rush", 31.0)
        tele("paddewwa_teleport", 64.0, CoordGrid(0, 48, 154, 26, 26))
        spell("blood_rush", 33.0)
        spell("ice_rush", 34.0)
        tele("senntisten_teleport", 70.0, CoordGrid(0, 51, 52, 57, 8))
        spell("smoke_burst", 36.0)
        spell("shadow_burst", 37.0)
        tele("kharyrll_teleport", 76.0, CoordGrid(0, 54, 54, 38, 17))
        spell("blood_burst", 39.0)
        spell("ice_burst", 40.0)
        tele("lassar_teleport", 82.0, CoordGrid(0, 46, 54, 60, 14))
        spell("smoke_blitz", 42.0)
        spell("shadow_blitz", 43.0)
        tele("dareeyak_teleport", 88.0, CoordGrid(0, 46, 57, 24, 48))
        spell("blood_blitz", 45.0)
        spell("ice_blitz", 46.0)
        tele("carrallanger_teleport", 94.0, CoordGrid(0, 49, 57, 22, 18))
        spell("smoke_barrage", 48.0)
        spell("shadow_barrage", 48.0)
        tele("annakarl_teleport", 100.0, CoordGrid(0, 51, 60, 24, 46))
        spell("blood_barrage", 51.0)
        spell("ice_barrage", 52.0)
        tele("ghorrock_teleport", 106.0, CoordGrid(0, 46, 60, 32, 32))
    }

    private fun editLunarSpells() {
        spell("lunar_home_teleport", 0.0)
        spell("bake_pie", 60.0)
        spell("geomancy", 60.0)
        spell("cure_plant", 87.0)
        spell("monster_examine", 61.0)
        spell("npc_contact", 63.0)
        spell("cure_other", 65.0)
        spell("humidify", 65.0)
        tele("moonclan_teleport", 66.0, CoordGrid(0, 33, 61, 2, 11))
        spell("tele_group_moonclan", 67.0)
        spell("cure_me", 69.0)
        tele("ourania_teleport", 69.0, CoordGrid(0, 38, 50, 36, 46))
        spell("hunter_kit", 70.0)
        tele("waterbirth_teleport", 71.0, CoordGrid(0, 39, 58, 50, 44))
        spell("tele_group_waterbirth", 72.0)
        spell("cure_group", 74.0)
        spell("stat_spy", 76.0)
        tele("barbarian_teleport", 76.0, CoordGrid(0, 39, 55, 47, 49))
        spell("tele_group_barbarian", 77.0)
        spell("spin_flax", 75.0)
        spell("superglass_make", 78.0)
        spell("leather", 81.0, suffix = "")
        tele("khazard_teleport", 80.0, CoordGrid(0, 41, 49, 12, 31))
        spell("tele_group_khazard", 81.0)
        spell("dream", 82.0)
        spell("string_jewellery", 83.0)
        spell("stat_restore_pot_share", 84.0)
        spell("magic_imbue", 86.0)
        spell("fertile_soil", 87.0)
        spell("boost_potion_share", 88.0)
        tele("fishing_guild_teleport", 89.0, CoordGrid(0, 40, 52, 51, 63))
        spell("tele_group_fishing_guild", 90.0)
        spell("plank_make", 90.0)
        tele("catherby_teleport", 92.0, CoordGrid(0, 43, 53, 49, 57))
        spell("tele_group_catherby", 93.0)
        spell("recharge_dragonstone", 97.5)
        tele("ice_plateau_teleport", 96.0, CoordGrid(0, 46, 61, 30, 34))
        spell("tele_group_ice_plateau", 99.0)
        spell("energy_transfer", 100.0)
        spell("heal_other", 101.0)
        spell("vengeance_other", 108.0)
        spell("vengeance", 112.0)
        spell("heal_group", 124.0)
        spell("spellbook_swap", 130.0)
    }

    private fun editArceuusSpells() {
        spell("arceuus_home_teleport", 0.0)
        tele("arceuus_library_teleport", 10.0, CoordGrid(0, 25, 59, 33, 62))
        spell("basic_reanimation", 32.0)
        tele("draynor_manor_teleport", 16.0, CoordGrid(0, 48, 52, 36, 23))
        tele("battlefront_teleport", 19.0, CoordGrid(0, 21, 58, 4, 27))
        tele("mind_altar_teleport", 22.0, CoordGrid(0, 46, 54, 36, 53))
        spell("respawn_teleport", 27.0)
        spell("ghostly_grasp", 22.5)
        spell("resurrect_lesser_ghost", 55.0)
        spell("resurrect_lesser_skeleton", 55.0)
        spell("resurrect_lesser_zombie", 55.0)
        tele("salve_graveyard_teleport", 30.0, CoordGrid(0, 53, 54, 40, 5))
        spell("adept_reanimation", 80.0)
        spell("inferior_demonbane", 27.0)
        spell("shadow_veil", 58.0)
        tele("fenkenstrains_castle_teleport", 50.0, CoordGrid(0, 55, 55, 28, 9))
        spell("dark_lure", 60.0)
        spell("skeletal_grasp", 33.0)
        spell("resurrect_superior_ghost", 70.0)
        spell("resurrect_superior_skeleton", 70.0)
        spell("resurrect_superior_zombie", 70.0)
        spell("mark_of_darkness", 70.0)
        tele("west_ardougne_teleport", 68.0, CoordGrid(0, 39, 51, 4, 27))
        spell("superior_demonbane", 36.0)
        spell("lesser_corruption", 75.0)
        tele("harmony_island_teleport", 74.0, CoordGrid(0, 59, 44, 21, 51))
        spell("vile_vigour", 76.0)
        spell("degrime", 83.0)
        tele("cemetery_teleport", 82.0, CoordGrid(0, 46, 58, 36, 51))
        spell("expert_reanimation", 138.0)
        spell("ward_of_arceuus", 83.0)
        spell("resurrect_greater_ghost", 88.0)
        spell("resurrect_greater_skeleton", 88.0)
        spell("resurrect_greater_zombie", 88.0)
        spell("resurrect_crops", 90.0)
        spell("undead_grasp", 46.5)
        spell("death_charge", 90.0)
        spell("dark_demonbane", 43.5)
        tele("barrows_teleport", 90.0, CoordGrid(0, 55, 51, 45, 50))
        spell("demonic_offering", 175.0)
        spell("greater_corruption", 95.0)
        spell("master_reanimation", 170.0)
        tele("arceuus_ape_atoll_teleport", 100.0, CoordGrid(0, 43, 142, 19, 13))
        spell("sinister_offering", 180.0)
    }

    private fun spell(name: String, xp: Double, suffix: String = "_spell") {
        edit("$name$suffix") { param[params.spell_castxp] = (xp * 10).toInt() }
    }

    private fun tele(name: String, xp: Double, dest: CoordGrid) {
        edit("${name}_spell") {
            param[params.spell_castxp] = (xp * 10).toInt()
            param[params.spell_telecoord] = dest
        }
    }
}
