package org.rsmod.api.combat.formulas.attributes

public enum class CombatMeleeAttributes {
    Crush,
    Stab,
    AmuletOfAvarice,
    SalveAmulet,
    SalveAmuletE,
    BlackMask,
    Arclight,
    BurningClaws,
    Obsidian,
    TzHaarWeapon,
    DragonHunterLance,
    DragonHunterWand,
    KerisWeapon,
    KerisBreachPartisan,
    KerisSunPartisan,
    BarroniteMaceWeapon,
    ForinthrySurge,
    RevenantWeapon,
    Silverlight,
    LeafBladed,
    ColossalBlade,
    RatBoneWeapon,
    InquisitorHelm,
    InquisitorTop,
    InquisitorBottom,
    InquisitorWeapon,
    OsmumtensFang,
    Dharoks,
    Gadderhammer,
    GadderhammerProc,
    KerisProc,
    BerserkerNeck,
    CorpBaneWeapon,
}
