package org.rsmod.api.combat.formulas.attributes

public enum class CombatWornAttributes {
    Crush,
    AmuletOfAvarice,
    SalveAmulet,
    SalveAmuletE,
    BlackMask,
    Arclight,
    BurningClaws,
    Obsidian,
    TzHaarWeapon,
    DragonHunterWeapon,
    KerisWeapon,
    BarroniteMaceWeapon,
    ForinthrySurge,
    RevenantMeleeWeapon,
    Silverlight,
    LeafBladed,
    ColossalBlade,
    RatBoneWeapon,
    InquisitorHelm,
    InquisitorTop,
    InquisitorBottom,
    InquisitorWeapon,
    OsmumtensFang,
    Dharoks,
    Gadderhammer,
    GadderhammerProc,
    KerisProc,
    BerserkerNeck,
    CorpBaneWeapon,
}
